### ISSUE TITLE
deploy on multiple vm or from remote vm

### ISSUE THREAD

**Issue by renghen** [Roblox/nomad-driver-iis#58]
hi to all,

from the use of it(I may be wrong), the files must be on the client running the iis and the win_iis driver, is there a way to make the deployment from remote, I mean from any nomad agent machine, and have the file transported to a windows server, just like for docker?

**Comment by robloxrob** [comment]
@Vulfox Can't you use the Artifact stanza for this?

**Comment by Vulfox** [comment]
Yea, the `artifact` stanza should still be applicable here. The nomad config needs to be updated to look for where the exe gets installed at and then followed up with a restart of the nomad service to register those changes. `template` stanza may help here or running a `raw_exec` script to update and run the commands.
